apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: shoekicks-20-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoekicks-20-client
  template:
    metadata:
      labels:
        app: shoekicks-20-client
    spec:
      containers:
      - name: shoekicks-20-client
        image: krrishexe/shoekicks-20-client:latest
        ports:
          - containerPort: 3000
        env:
        - name: REACT_APP_STRIPE_PUBLISHABLE_KEY
          value: pk_test_51OssNiSA8M310S6LeHyVt8yxauM3FyK0cR8DVtmwPFdMc08a7sEA6NpGthdMS4Q4eGpm119fpLCXJeaVCghhlMg500wfIgmenm