apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port your frontend application listens on
      targetPort: 3000  # Port your frontend application listens on
  type: LoadBalancer
